---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-publisher
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: tx-publisher
  template:
    metadata:
      labels:
        app: tx-publisher
    spec:
      containers:
        - name: tx-publisher
          image: tx-publisher:alpha
          imagePullPolicy: Never
          env:
            - name: RABBIT_HOST
              value: 'rabbit'
            - name: RABBIT_PORT
              value: '5672'
