apiVersion: batch/v1
kind: Job
metadata:
  name: transaction-service-db-migration
spec:
  template:
    metadata:
      name: transaction-service-db-migration
      labels:
        app: transaction-service-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: transaction-service-db-migration
          image: transaction-service-db-migrate:alpha
          env:
            - name: TRANSACTIONS_DATABASE_URL
              value: 'postgresql://postgres:example@postgres:5432/postgres?schema=public'
