apiVersion: batch/v1
kind: Job
metadata:
  name: product-inventory-service-db-migration
spec:
  template:
    metadata:
      name: product-inventory-service-db-migration
      labels:
        app: product-inventory-service-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: product-inventory-service-db-migration
          image: product-inventory-service-db-migrate:alpha
          env:
            - name: PRODUCT_INVENTORY_DATABASE_URL
              value: 'postgresql://product_inventory_user:fcgvIOF5V0OEqwZwGYQj%2FrZDjYzAeaIKe%2BczqSz%2FGKQ%3D@localhost:15432/product_inventory?schema=public'
