apiVersion: batch/v1
kind: Job
metadata:
  name: product-inventory-service-db-migration
spec:
  template:
    metadata:
      name: product-inventory-service-db-migration
      labels:
        app: product-inventory-service-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: product-inventory-service-db-migration
          image: product-inventory-service-db-migrate:alpha
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:example@postgres:5432/postgres?schema=public'
