---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: product-inventory-service
  template:
    metadata:
      labels:
        app: product-inventory-service
    spec:
      containers:
        - name: product-inventory-service
          image: product-inventory-service-service:alpha
          imagePullPolicy: Never
          env:
            - name: PORT
              value: '8000'
            - name: PRODUCT_INVENTORY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: product-inventory-service-secrets
                  key: PRODUCT_INVENTORY_DATABASE_URL
            - name: RABBIT_HOST
              value: 'rabbit'
            - name: RABBIT_PORT
              value: '5672'
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
            - name: QUEUE_DEFAULT_ATTEMPTS
              value: '5'
            - name: QUEUE_DEFAULT_BACKOFF
              value: '{"type": "exponential", "delay": 1000}'
            - name: QUEUE_DEFAULT_REMOVE_ON_COMPLETE
              value: '{"age": 60000, "count": 200}'
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: product-inventory-service
spec:
  selector:
    app: product-inventory-service
  ports:
    - port: 8000
